### ISSUE TITLE
Issue on Windows console

### ISSUE THREAD

**Issue by DRSDavidSoft** [kint-php/kint#201] opened 2016-05-19 16:40 UTC
Calling `s()` from console works great in Linux, however in Windows it doesn't show the unicode table drawing characters correctly.
<img src="https://i.imgur.com/T7iQiph.png" />

I accept anything ranging between:  
a) disable these characters altogether,  
b) replace them with ordinary dashes and pipelines, or
c) create a fix to show them correctly on Windows.

**Comment by raveren** [comment] 2016-05-24 11:50
Hey, thank you for the issue, I had trouble with this in previous iterations, but should be fixed now. Are you using the current Kint version? 

Sidenote, if you want a quick workaround call `~d($var)`, but please help me debug the issue with you, so - newest version? What's the windows version?

**Comment by raveren** [comment] 2016-05-24 11:55
can you open a cmd console and launch `echo %ANSICON%` and `echo %ConEmuANSI%` and let me know the result. After doing this, can you launch the command in this answer: http://stackoverflow.com/a/388500/179104 and see if it helped. 

A huge thanks for helping me out with this :)

**Comment by DRSDavidSoft** [comment] 2016-05-24 16:10
Sure thing, @raveren!

> call `~d($var)`

Unfortunately, this yields _exactly_ the same results as `s($var)`.
Judging by the docs, I thought this was just an alias for the text dump?

---

> `echo %ANSICON%` and `echo %ConEmuANSI%`

I did a `set` query for both variables, and it seems they're NOT defined in my workspace.

```
Environment variable ANSICON not defined
Environment variable ConEmuANSI not defined
```

Judging by the `ConEmuANSI` variable, I believe it is meant for the ConEmu console emulator, which I have installed, but not used during tests.  
Sidenote: Kint have this Unicode issue on both Windows' own terminal _and_ on ConEmu. Hopefully, a proper fix would work on both terminals, not just one of them.

---

> `chcp 65001`

Sorry, but no effects. I did both:
- Opening a new terminal, using the command, closing the terminal and opening the PHP file.
- Opening a new terminal, using the command, loading my PHP app through PHP's command-line. (Which I believe was the intended way.)

(I think it shows a _different_ wrong character when doing `chcp`. Maybe a different code page?)

---

> newest version?

I just cloned the git source to my working directory before reporting this issue.  I know it's a real pain when people report issues on the earlier versions when they might have been fixed in the latest version.

Sidenote 2: I was using a version from 2013's prior to the upgrade. That version also had the same problem.

---

>  What's the windows version?  

I'm using Windows 10 for testing this, although I don't believe other versions would make a difference. Another possibility is using a clean installation, but again I doubt it would matter.

Here's the build number I'm using at the time of writing this:
`Microsoft Windows [Version 10.0.10586]`

---

_PS:_

I was using a custom-built version of PHP cli  for my app, but decided to use PHP's official binaries while debugging this issue as to remove any chance of different configurations and/or unexpected results. However please be aware that that this issue happens on both my custom built `exe` _and_ php's own windows binaries. (Using PHP 5.x and also PHP 7.x).

For now, I am using Kint's `s()` on my Linux environment instead of Windows, until the Windows' version gets fixed.

---

> A huge thanks for helping me out with this :)

@raveren, you're absolutely welcome!  

Actually, it's me that has to thank you for the greatest PHP debugging tool ever. I have been using Kint for the past three years, and I'd like to show my deepest gratitude for this project.  
I just hope I can help in more ways in the code, rather than just debugging this.

---

Although using these modifiers like this is a pretty clever idea, if Ican get rid of those characters for now (or even permanently with a modifier like `%`), it would be awesome. I just want a way to dump a JSON-like array in the terminal.  xdebug (While being much better than `print_r()`, is just horrible (comparing to the awesome Kint!)

Also, in the mode described above, turning off the line tracing would be also useful. Maybe using '@'` modifier for both 'd()' and 's()'?

As much as I want this to be fixed sooner, there is no rush. I can use my Linux environment for this instead of Windows until it is done.

**Comment by jnvsor** [comment] 2016-05-24 16:41
> I know it's a real pain in the b***t when people report issues on the earlier versions, while it was fixed in the latest.

To be fair, @raveren hasn't tagged a release in 1 human pregnancy

**Comment by raveren** [comment] 2016-05-25 08:08
@jnvsor :D sorry, as I commented in the other thread, PHP is no longer my main language and I had a personally rough patch, but I am returning to working on Kint.

@DRSDavidSoft wow, thanks for the kind words, I'm so happy it helped you - that's exactly my goal that I've been working at for all of those years, no detail is too small in a tool you use daily, let's sort this one out :)

> a proper fix should work on both terminals, not just one of them. ;)

I hoped that was already the case, I used to work on Kint on my two different windows machines - different windows versions, one configured for work and other mainly as a media server, I hoped that would cover most of the cases, but evidentially it did not. 

The inner working is Kint uses utf8 characters to decorate cli output by default and it (should!) automatically detect windows and use the symbols from the middle set instead:

``` php
    private static $_utfSymbols      = array(
        '┌', '═', '┐',
        '│',
        '└', '─', '┘',
    );
    private static $_winShellSymbols = array(
        "\xda", "\xdc", "\xbf",
        "\xb3",
        "\xc0", "\xc4", "\xd9",
    );
    private static $_htmlSymbols     = array(
        "&#9484;", "&#9604;", "&#9488;",
        "&#9474;",
        "&#9492;", "&#9472;", "&#9496;",
    );
```

it does not, however! That means `kint/decorators/plain.php:211

``` php
$inWindowsShell = PHP_SAPI === 'cli' && DIRECTORY_SEPARATOR !== '/';
```

results in false - _or_ the `\xd9` symbols still look bad in your version in cmd.exe.

I will have to investigate this further, my plan is to create vagrant boxes since I now only have the one win10 machine that I only use for media playback nowadays, my other gear is os x or ubuntu.

Note, the `~` modifier, contrary to what I implied, always returns the plain, whitespace separated utf8 encoded output regardles of the context (be it web or CLI). 

Again, thanks for the kind words, I promise to devote as much time as possible to Kint in the coming months.

**Comment by raveren** [comment] 2016-05-25 08:53
@DRSDavidSoft oh and about the themes, I'm writing them using the LESS preprocessor, so you need node to compile it and a very shallow learning curve if you know css already. Having said that, themes are far from realistically ready for contributors, the HTML markup is not documented for example, but that is not in my priority list for now :/

**Comment by jnvsor** [comment] 2016-05-25 16:41
@raveren My only gripe with less in kint is that (As far as I can see) you have to compile them seperately. sass and the like can just do the whole folder at once, but combined with grunt or gulp you could do all the less and js compilation in one go. (But now we're getting off track)

**Comment by DRSDavidSoft** [comment] 2016-05-25 18:21
As a side note about the themes, I haven't had yet a reason to use pre-processors in CSS, I know for a fact that both less and sass are great, I have looked over their syntaxes, but for some reason, I always tend to go against writing non-pure CSS code - as once I was against jQuery and pretty much insisted to write only vanilla javascript instead; although I'm starting to use more of the CSS pre-processors in my projects -- as less is something I've delayed to learn enough. I think it'll be easy as I already am very familiar with CSS.

I know documentation is not currently on the priority list, but please keep it in the list of things that need to be done, in time. I'd be glad if I can help in any way regarding that.  
However, please don't feel pressured if you have switched to other programming languages, I know that'll happen at least once in every dev's life. I know it has happened to me more than once!

Leaving this matter, for now, I think I have ideas on how to fix decorations, maybe in a new issue or even a pull request. As I've said before, I want to help this project as much as I can, just like Kint help me much in the past. Please let me know if I can get involved in any way.

**Comment by DRSDavidSoft** [comment] 2016-05-25 18:31
<s>First of all, I'm sure that `~d($var)` does really outputs the decorated text, not whitespaced. Could you work on that? I'll look into plain.php now.</s> I found that the issue comes from something else. I will work on that.

Also, is there a full alternative to `s()` like `Kint::plain()` as it to `d()` for `Kint::dump()`? 

---

### Update: I will add to this comment as I do my research.

1) Confirmed that printing the raw `$_winShellSymbols` data actually draws the Unicode decoratives correctly.  Both on `cmd.exe` and `ConEmu.exe`. I will only test on Cmd as of now because I think there would be no difference between their output.

2) When I tested out the above, my active code page was set to 720. (i.e. `chcp 720`) which is the default in Windows, I think.

3) Using other fonts and changing code page in not reliable to work at all.  I'm sticking to using `$_winShellSymbols` and make it work under Windows.

4) Can confirm that `$inWindowsShell` is indeed `TRUE` within a Windows environment.

5) Even with `Kint::enabled()` set to `Kint::MODE_WHITESPACE`, I am still getting bad characters on the screen. <s>Maybe something is up with this bit of code: `str_repeat( $char, $repeat )`? That's sneaky.</s> scratch that <s>No, but in line 204 for `$char` I am still getting utf-8 decoratives, _even_ when `::enabled` is set to `w`. Weird! Gotta trace that function first.</s>

Nope, nope, I think I got what you're doing here. `_char()` is simply meant to replace the utf-8 decoratives into their proper forms for each shell. Let me try something first...

Success! I'm getting somewhere now, I think

**6) `array_search( $char, self::$_utfSymbols, true )` is <s>returning false. This can't be good.** Let's look up the repo for that function...</s> all good, my bad. But I know where to look for the problem

**7) Head's up! calling `s()` and then checking `Kint::enabled()`, it is still set to '`w`'! I forced the mode to be on '`c`', and it works great!** Also, why on earth `case Kint::MODE_WHITESPACE:` is empty? it should set `$char` to `''` or `' '`, shouldn't it?

---

Update:

Doing this works great for me!

```
    Kint::enabled('c');
    Kint::dump($var);
```

I do, however, would like to change that hard-coded 78 widths so it can adapt to my window size.

**Comment by jnvsor** [comment] 2016-05-25 18:35
`s()` just sets `Kint::enabled()` then calls `Kint::dump()`

**Comment by DRSDavidSoft** [comment] 2016-05-25 18:39
@jnvsor Thanks! May I ask how does that translate to plain output?

**Comment by jnvsor** [comment] 2016-05-25 18:45
Kint decides [which decorator](https://github.com/raveren/kint/blob/master/Kint.class.php#L200) to use based on the enabled mode, and the decorator optionally has it's own behaviour based on it

@raveren I was planning on pushing a large branch this weekend as an RFC. It touches pretty much every single line and does a cleanup of lots of less logical parts of the plumbing (Html coming from a parser, decorators parsing themselves, parser being a child of the data object etc) plus makes the whole thing more pluggable etc etc.

Currently it stands at `60 files changed, 3796 insertions(+), 3839 deletions(-)` compared to raveren/master. Long story short if you could push your changes towards the start of the weekend that would help me get my branch up to date before the end of it

**Comment by DRSDavidSoft** [comment] 2016-05-25 19:34
### List of fixes (TBU) - I might do a PR soon about these soon
1. On `plain.php`, line 219, after `case Kint::MODE_WHITESPACE:` and `default:`, add this:
   `$char = ' ';`
2. On `Kint.class.php`, line 809, change `MODE_WHITESPACE` to `MODE_CLI`, like this:
   `PHP_SAPI === 'cli' ? Kint::MODE_CLI : Kint::MODE_PLAIN`

**Comment by jnvsor** [comment] 2016-05-25 19:43
GJ - make a PR for it :)

**Comment by DRSDavidSoft** [comment] 2016-05-25 19:45
@jnvsor I would, but it seems they are already a lot of other forks, also I wanted to ask your opinion before doing so. Do you verify them?

**Comment by jnvsor** [comment] 2016-05-25 19:47
Lots of people on github don't understand how git works. They think forking something is liking it. I'm guessing most of those forks are empty.

There are currently 10 PRs (4 of which are mine!) and yes @raveren checks them all before commiting. A bit too thoroughly if you ask me - nothing wrong with a revert every now and then :)

That said we should probably stop here - we're approaching 20 comments and most of them have nothing to do with the issue :)

**Comment by raveren** [comment] 2016-05-25 20:09
Guys, please keep the thread on topic. 

In reply to https://github.com/raveren/kint/issues/201#issuecomment-221665086: so the problem is in detecting Kint modes? What initializer code are you using? Try

``` php
    Kint::enabled(true);
    Kint::dump($var);
```

what do you get? Does `d()` work in cli? One nuance I forgot when sorting out the mode logic is that indeed `WHITESPACE` displays terribly in windows shell because of the utf8 symbols. I'll have to think this through, but I'm too tired today, thanks for the resarch!

@jnvsor I'm sorry, but there is no way I can get my changes out this week, but please don't discuss this in this thread.

**Comment by DRSDavidSoft** [comment] 2016-05-25 20:20
@raveren Yes, Indeed those works well!
Using both methods, I get this:
<img src="https://i.imgur.com/Uoppksg.jpg?1" />

Can you fix the `s()` problem? I am working on my fork to fix some other console issues on Windows, but I edited what I thought was needed to make `s()` work correctly. Would be glad if you review my edits! :)

https://github.com/DRSDavidSoft/kint

**Comment by raveren** [comment] 2016-05-25 20:26
That's the windows console nuance I mentioned, as for your changes, I pushed the whitespace around already in my private build, I'll publish it next week, and the console width only affects the decorative separators inbetween dumps, so it shouldn't impede readability (I use widescreens too), the 80 char width is a compatibility feature, but I'm sure there're ways to determine real actual console char width, I'm just not sure whether it'd be a real improvement (resizing the window would render everything unreadable for eg.)

**Comment by DRSDavidSoft** [comment] 2016-05-25 20:36
@raveren Great! Hope to see those updates sooner. About the console width, I assure you it is a really useful improvement, that resizing matter has mostly fixed on Windows, and also once the window is properly resized, this feature is the best thing devs can ask for. One simple example is the following scenario: (On windows)

```
mode 30,10
title Example PHP CLI Program
php file.php
REM the above uses Kint inside a 30x10 Windows
```

As you can see, this will really help, and in my opinion is even a necessity.
Even most Linux programs (like nano) adjusts to the console dimensions.

I know it's super easy in C++, but don't know how to do it using PHP. I'll look it up on Google.

Thanks again!

P.S. I forced colors to be always enabled, and it works great. Even though `ANSICON` is not `true`.
Maybe also remove `DIRECTORY_SEPARATOR === '/'` so colors work on ConEmu for Windows?

But I don't know, what about Windows' own terminal?

**Comment by raveren** [comment] 2016-05-26 07:47
I made an experiment with the `s()` and `d()` functions, you can try it out yourself, but I will do some rigorous testing later:

``` php
    function s()
    {
        $enabled = Kint::enabled();
        if ( !$enabled ) return '';

        if ( $enabled === Kint::MODE_WHITESPACE ) { # if already in whitespace, don't elevate to plain
            $restoreMode = Kint::MODE_WHITESPACE;
        } else {
            if (PHP_SAPI === 'cli') {
                $restoreColors = Kint::$cliColors;
                Kint::$cliColors = false;
            } else {
                $restoreMode = Kint::enabled( Kint::MODE_PLAIN );
            }
        }

        $params = func_get_args();
        $dump   = call_user_func_array( array( 'Kint', 'dump' ), $params );

        isset( $restoreMode ) and Kint::enabled( $restoreMode );
        isset( $restoreColors ) and Kint::$cliColors = $restoreColors;
        return $dump;
    }
```

**Comment by raveren** [comment] 2016-09-21 15:02
I don't see an issue any more, closing this.

**Closed as completed by raveren** 2016-09-21 15:02 UTC

**Comment by DRSDavidSoft** [comment] 2022-01-02 12:27
Actually fixed for good with the recent Windows 10/11 updates in #319! ❤️
