### ISSUE TITLE
New deprecations in PHP 8.1

### ISSUE THREAD

**Issue by kenjis** [kint-php/kint#374] opened 2021-12-18 05:49 UTC
kint-php/kint 3.3

I got the error:
> strlen(): Passing null to parameter #1 ($string) of type string is deprecated 
> VENDORPATH/kint-php/kint/src/Renderer/RichRenderer.php at line 329

How to reproduce:

```php
d('example');
```

Browsing the page with a web browser.

**Comment by jnvsor** [comment] 2021-12-18 09:54
@kenjis I'll be releasing 4.0 later today, but I can't reproduce this with 8.1 and 3.3 either.

Can you try 4.0-beta1 to check it's not happening there in the meantime? If it's an edge case I can't reproduce the new release won't help you

**Comment by kenjis** [comment] 2021-12-18 09:59
@jnvsor Thanks! Where is upgrade guide?
I got the error:
> Access to undeclared static property Kint\Kint::$max_depth

**Comment by jnvsor** [comment] 2021-12-18 10:03
Yeah one of the breaking changes is that `$max_depth` was renamed `$depth_limit` so if you're setting that yourself you'll have to rename it. Other than that and the `d(1)` trace handling unless you're writing plugins it should just be a drop in replacement

**Edit:** I see, a deprecation warning. Surprised psalm didn't catch that. I'll fix this before release

**Comment by kenjis** [comment] 2021-12-18 10:11
I got the same error, and changed the following lines (just added `(string)`) and worked.

src/Renderer/RichRenderer.php: L329
```php
            if (\strlen((string) $result)) {
```

src/Zval/Value.php: L134
```php
        if (\strlen((string) $out)) {
```

**Comment by jnvsor** [comment] 2021-12-18 10:40
Hi @kenjis I'm just going to use this issue as a catchall for new deprecations in 8.1, since I've found a few others as well. I've pushed the fix for this specific one to master but I have fixes incoming for the color and xml plugins too.

In the meantime can you confirm that deprecation notice goes away with `@dev-master`?

**Comment by kenjis** [comment] 2021-12-18 11:26
Okay! It worked with `dev-master`.

**Comment by jnvsor** [comment] 2021-12-18 15:48
As of a913d1151050344ad73c55d5470a8bd23e49c669 I _think_ I've caught all the deprecation warnings but there may still be edge cases.

I won't consider them "We need an immediate bugfix release" worthy (They're just notices after all) but if anyone finds any more I'd appreciate new issues.

Thanks for spotting it @kenjis

**Closed as completed by jnvsor** 2021-12-18 15:48 UTC
Labels: bug

**Comment by kenjis** [comment] 2021-12-19 07:32
@jnvsor Thank you for your quick fixes.

I've found another renamed property, `Kint\Renderer\RichRenderer::$object_plugins`.
https://github.com/kint-php/kint/commit/44c8e2905be7a054dbe410c46fa75a6c2440c7bd#diff-9f248ed65b13b3a98c776cbd20903cebfead78d1fbe278a76f3fb2b4f6b04a9aL40

It would be nice it is added to the release note.

**Comment by jnvsor** [comment] 2021-12-19 12:58
Thanks @kenjis, I've updated it
