### ISSUE TITLE
Put composer.lock in .gitignore and drop it from the repo

### ISSUE THREAD

**Issue by kktsvetkov** [kint-php/kint#342] opened 2020-08-12 20:55 UTC
While it is a good practice to put your `composer.lock` in version control so that you can track the state of your project deployed dependencies, that's not the same for libraries such as this one. It is metadata, and it changes for new deployments since the dependencies have newer versions, or newer requirements (like php8), and so on. 

For example, current `composer.lock` is 6 months old, and after cloning Kint locally it is already changed
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   composer.lock
```

So let's put `composer.lock` in `.gitignore` and drop it

**Comment by jnvsor** [comment] 2020-08-13 09:25
It's committed because it contains the tests, the build tools, and the formatters. This way we can check the code formatting and reproducible build in CI.

If you drop the lockfile, updates to the code formatter might change multiple pieces of code unrelated to your changes, or other dependencies might change the phar. We've had a reproducible build for quite a while and I'd like to keep it that way.

So to remove the lockfile we'd have to manually specify exact versions to install in the travis.yml *and* it would force everyone to update them in travis.yml every time they make a change *and* everyone would have to update their dependencies to at least that version when pulling someone else's changes. That's basically what the lockfile does.

Kint itself has no dependencies (besides php), only dev-dependencies. The lockfile isn't used by composer when requiring kint either, so there are no technical downsides to keeping the lockfile.

All of this is ditto for npm's `package-lock.json`

If you need to update the dependencies for some reason (IE new code formatters to clean stuff up) go right ahead and make a separate commit for it. That way we can tell code formatting/build process changes from actual changes to the code. Otherwise just `composer install` from the committed file and don't bother updating.

If you've thought of something I missed leave another comment.

**Closed as completed by jnvsor** 2020-08-13 09:25 UTC
