### ISSUE TITLE
Output twice

### ISSUE THREAD

**Issue by eno812** [kint-php/kint#210] opened 2016-08-09 02:35 UTC
I'm very new to Kint so I'm sure there is an easy explanation for why the output (dump) is happening twice. Once with the call stack and once without.

How do I remove the output without the call stack?

**Comment by raveren** [comment] 2016-08-09 07:09
This is not usual but it's not a bug of Kint, if you provided more details, I could help you figure it out, what do you mean by call stack?

**Comment by eno812** [comment] 2016-08-09 09:10
Hi,

Thanks for your reply but somehow it's not longer a problem.  I'm not sure
what it was but if it appears again I'll copy the code and ask for your
help.

Cheers,
Ian

**Comment by raveren** [comment] 2016-08-09 09:36
alright, I'm closing the issue then :)

**Closed as completed by raveren** 2016-08-09 09:36 UTC
