### ISSUE TITLE
Bugged output when array value is forward slash

### ISSUE THREAD

**Issue by gcaplan** [kint-php/kint#152] opened 2015-06-23 14:34 UTC
Hi

When dumping an assoc array with `d($my_array)` I'm getting incorrect output if the value is a forward slash. Single or double quoting the value makes no difference. Array seems to be correctly formatted, and output with `print_r($my_array)` is as expected. 

Array:

``` php
<?php
  $vals['routes'] = [
        ['GET', '/', false, 'indexViewModel'],
        ['POST', '/checkout/submit/', 'checkoutSubmitController', false],
        ['GET', '/product/:mixed/', 'false', 'productViewModel'],
    ];
```

Here's the scrambled output. It's interpreting the single slash in the first route as a directory, while the more complex paths are handled correctly. It's pulling the slash out of the array grid and displaying it separately. The subsequent values for that line of the grid are shifted one column to the left. All other values I've tried work OK - it's the single forward slash that's the issue, I think.

Am I misunderstanding something? This behavior is surely not by design, but it seems surprising that such a bug wouldn't have been reported before...

![image](https://cloud.githubusercontent.com/assets/454592/8308264/c9e23800-19bb-11e5-949d-a9f793674a83.png)

**Comment by raveren** [comment] 2015-06-23 15:21
Hello, the issue has been fixed in a previous version, but this means I must be fumbling around in my composer definitions, I updated the readme to state that the `composer.json` should look like this:

``` json
"require": {
   "raveren/kint": "^1.0"
}
```

Then run `composer --update` to get the newest 1.0.2 and see if the issue is fixed.

I'm really sorry for the trouble.

**Comment by gcaplan** [comment] 2015-06-23 15:53
Wow - how's that for a fast reponse! Your suggestion did the trick. Like many, I suspect, I'm a bit baffled by Composer upgrade policies, so I just tend to copy and paste the author's recommendation without checking if it's up to date. Shouldn't be so lazy... Many thanks for your help.

![image](https://cloud.githubusercontent.com/assets/454592/8310491/30505160-19c8-11e5-81de-119135968025.png)

**Comment by raveren** [comment] 2015-06-23 15:55
If you're wondering, Kint misinterprets the '/' as a directory, but that's because apache can reach your server root (php checks for `is_readable`) - which might be a slight indication to do a permissions supervision unless this is not a production server :)

Glad I could help :)

**Closed as completed by raveren** 2015-06-23 15:55 UTC

**Comment by gcaplan** [comment] 2015-06-23 16:08
Thanks for the security heads-up - it's only a dev server but root shouldn't be readable. I'm just setting it up and I must have messed up my permissions. I'll check them now!
