### ISSUE TITLE
Regression of the trace display

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#305] opened 2019-03-09 04:47 UTC
I've been using Kint for real work lately and I see three regressions for the worse: 

1. The surplus unintuitive wrapper at the bottom of the page - comes by default as well.
2. No more `dd` - number one feature, one of the main ones that Symfony lifted off us writing their own VarDumper. Everyone everywhere misses it.
3. The trace display used to be great:
![image](https://user-images.githubusercontent.com/364220/54066317-952e0880-4236-11e9-9da3-a1f3266cb6ae.png)
now it's fugly and useless:
![image](https://user-images.githubusercontent.com/364220/54066335-db836780-4236-11e9-8df3-f046f6d1f1e0.png)

While the first two can be configured manually, the trace display is gone for good and I've no idea how to reimplement it with the current code structure, any ideas, @jnvsor?

**Comment by jnvsor** [comment] 2019-03-09 09:14
1. I found using kint with any kind of HTML layout difficult when it was forced into a small width box. I'd rather default to something that's readable no matter where it'd dumped on the page. Alas browsers will still mess it up if you dump in between table rows and there's nothing you can do about that in JS :(
2. Yes symfony and laravel used `dd` and then people complained that they and kint were breaking eachother so you made `ddd` as well but `dd` was still broken (#170) It's a one-liner to implement, so I still prefer it this way. Less headaches.

    > one of the main ones that Symfony lifted off us writing their own VarDumper

    They lifted it off laravel, who lifted it off drupal IIRC
3. I understand the line numbers aren't convenient. Spent a lot of time trying to get them to work in a way that let you copy paste the code snippet properly and decided to just mark the lines on top. Flexbox would probably be the easiest fix - are we willing to drop browser support like that?

    Are there any other issues besides the line numbers?

**Comment by raveren** [comment] 2019-03-09 13:04
It's not just the line numbers, it was displayed completely differently from the current way which looks like it's a blotched on afterthought.

> They lifted it off laravel, who lifted it off drupal IIRC

Uh-huh, lifted off the fantastic feature rich well known variable dumper that was laravel's `dd` at the time :)

Anyway, I propose returning `ddd`, no reason not to, it's a no brainer, do you agree?

Furthermore, especially after reading #295 #293 #285 and etc etc I propose removing the default wrapper display and placing it into an opt-in.

Do you actually *use* Kint, @jnvsor? The wrapper obscures information by dismantling page flow, it's counter-intuitive and an **extra click every time you dump stuff out**, Kint is a productivity tool, if you have a preference on how to display it subjectively prettier - it's fine, but not do it by default!

Do you agree with those?

As for trace, this is definitely a hard regression, I hope I will be able to add a new, custom trace display as it was in v1.1, if you have any ideas where to begin, I'd appreciate it.

**Comment by jnvsor** [comment] 2019-03-09 13:52
> It's not just the line numbers, it was displayed completely differently from the current way which looks like it's a blotched on afterthought.

... Tried dumping an exception yet? Exceptions have backtraces as well, and these are displayed as normal arrays in the old code.

In order to make traces work everywhere they're now handled like all plugins which means if there's a trace in the data you'll see it as a trace. It's not a special mode that does something entirely different from normal dumping.

> As for trace, this is definitely a hard regression

I see 5 differences between the old trace and the new one:

1. No line numbers (Can be fixed)
2. Line range was added at the top (Because of 1)
3. The color of the highlighted line (Big whoop)
4. Numbers per frame before the open button. Ignoring the low hanging fruit like "arrays don't start at 1" this was plain old inaccurate in the old code as well because you [removed frames from the trace](https://github.com/kint-php/kint/blob/1.x/Kint.class.php#L647)
5. The base `Kint::trace()` dumps the trace itself, not the frames individually. This was done for consistency between `Kint::trace()` `Kint::dump(1)` and `Kint::dump(debug_backtrace())`

> Do you actually *use* Kint, @jnvsor?

Yes. And I like being able to see backtraces if there's an exception.

Again: Do you have anything specific besides the line numbers or are you really summing this up as "It's fugly and useless"?

**Comment by raveren** [comment] 2019-03-09 18:11
Yeah, the trace in the exception is quite useful, but is still very difficult to read, I don't understand how can you not agree with this. The good old trace display was objectively better, just look at the screenshots in OP and tell me it's not, man.

Also, there's a difference number 6: the old trace did not come in a wrapper, but I agree, when displaying trace amongst other elements the wrapper is an advantage.

Of course I am dropping useless frames which just confuse, and the trace starts from one cause you read it that way, I don't understand your points.

BTW I have written and am still improving a custom error handler for many years, maybe during the current project I'm working on I'll make it sufficiently universal to opensource as well.

![image](https://user-images.githubusercontent.com/364220/54075382-5e440b00-42a7-11e9-8d75-585f3ce3d5bb.png)

**Comment by jnvsor** [comment] 2019-03-09 19:20
> The good old trace display was objectively better, just look at the screenshots in OP and tell me it's not, man.

Sorry I'm genuinely not seeing it, that's why I went out of my way to list the differences. I agree with the line numbers though.

Are we talking about functional differences or style differences like line height or something? Font size? (The old one just looks bigger because it's a smaller screenshot)

> Also, there's a difference number 6: the old trace did not come in a wrapper, but I agree, when displaying trace amongst other elements the wrapper is an advantage.

That's what I meant with point 5

> Of course I am dropping useless frames which just confuse, and the trace starts from one cause you read it that way, I don't understand your points.

The numbers might be read as saying "Oh it's number 5 so I need to look at `debug_backtrace()[5]`" which isn't right of course. Since 2.x the access paths have shown an accurate index (From the perspective of the dump call location) so this is less important anyway.

> BTW I have written and am still improving a custom error handler for many years, maybe during the current project I'm working on I'll make it sufficiently universal to opensource as well.

Tip: [FlattenException](https://api.symfony.com/4.0/Symfony/Component/Debug/Exception/FlattenException.html) - I wrote an error handler that sends me emails when something goes wrong, and some of the emails were too big to send... That will make it a lot less painful (But less info to see of course)

**Comment by jnvsor** [comment] 2019-03-20 17:17
I spent a day or 2 trying to find out why the damned copy paste wasn't working and ended up filing a bug report for firefox after reproducing it.

I have a patch with a workaround in the pipe:

![image](https://user-images.githubusercontent.com/5260644/54705040-3c1a7a80-4b3c-11e9-98ce-270b406c0058.png)

That's with line numbers added (And they don't get copied when you drag or triple click select)

Do you have anything else concrete? If not I'll close this when I merge that ^

**Comment by raveren** [comment] 2019-03-20 18:14
Woow!! Pretty amazing, great job!

**Comment by jnvsor** [comment] 2019-03-20 20:27
Pushed in c2aa6abf8c7d430d34d0f4b5825f25a897db4cc8

**Closed as completed by jnvsor** 2019-03-20 20:27 UTC
