### ISSUE TITLE
PHP 8.1 issue - passing a null parameter

### ISSUE THREAD

**Issue by j2s** [kint-php/kint#397] opened 2022-11-11 20:44 UTC
Using PHP 8.1 I see:
Deprecated function: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in Kint\Renderer\RichRenderer->renderChildren() (line 329 of vendor/kint-php/kint/src/Renderer/RichRenderer.php).

Deprecated function: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in Kint\Object\BasicObject->getModifiers() (line 134 of vendor/kint-php/kint/src/Object/BasicObject.php).

This is in in v3.3 (used in Drupal 9) but also seems to be present in current version 4.2.0 (for RichRenderer.php)

This is documented in https://www.php.net/manual/en/migration81.deprecated.php
The fixes are straightforward changing strlen() for !empty() etc

**Comment by jnvsor** [comment] 2022-11-11 21:11
This should have been fixed in 7299750767f50015eff7e5a5d7407367716adc3e - are you sure you're using 4.x? Can you tell me which line it's occurring on in 4.2.3?

**Comment by j2s** [comment] 2022-11-12 09:37
Hi Jonathan
Seems to be in 4.2.0
    public function renderChildren(Value $o)
    {
        $contents = [];
        $tabs = [];

        foreach ($o->getRepresentations() as $rep) {
            $result = $this->renderTab($o, $rep);
            if (\strlen($result)) {
                $contents[] = $result;
                $tabs[] = $rep;
            }
        }

**Comment by jnvsor** [comment] 2022-11-12 10:09
Yes I know what the code looks like, but what line is the error message reporting exactly? There's no code path in `renderTab()` that would return a null, they all return strings so this error can't be happening there in 4.x.

Otherwise, what's your input data? Can you give a snippet to reproduce it?

**Comment by j2s** [comment] 2022-11-12 12:06
Hi
I encountered the problem in Drupal 9 which uses v3.3. I then had a look at the latest 4.x code and could see that the same related line was there - in 3.3. its    329:       if (\strlen($result)) {
I tried to get the latest kint to load via composer but there were too many conflicts.
If you feel the strlen() will now never have a null value - then that is all good!
I need to see how to get the Drupal devel module to pull in the 4.x code
Thanks for your work on this

**Comment by jnvsor** [comment] 2022-11-12 12:22
Alright, then I'm going to close this

> I tried to get the latest kint to load via composer but there were too many conflicts

Kint only has php version and dev dependencies. If their version requirements are too strict you should be able to load the phar and load composer autoloader in append mode as a hacky workaround

**Closed as not planned by jnvsor** 2022-11-12 12:22 UTC

**Comment by j2s** [comment] 2022-11-15 10:44
Drupal users see https://gitlab.com/drupalspoons/devel/-/issues/416  on how to update
