### ISSUE TITLE
Kint modifying internal variables... fatal error

### ISSUE THREAD

**Issue by SrikalyanBurra** [kint-php/kint#245] opened 2017-06-20 16:04 UTC
a mere Kint::trace() call is conditionally causing serious issues. In some cases its working fine but in certain places(like the one mentioned below) it is modifying my internal variable.

![del](https://user-images.githubusercontent.com/20722446/27343023-5761ea96-55ff-11e7-974a-542ed5a6e3ea.png)

If I just remove the trace, its working fine. Originally that variable is an array, but after calling d(1) the variable became 'Kint_Object_Instance'.
this is quite surprising. Any help is greatly appreciated 

cheers!!

**Comment by jnvsor** [comment] 2017-06-20 16:18
Dupe of #246

**Closed as completed by jnvsor** 2017-06-20 16:18 UTC
