### ISSUE TITLE
Bugged on classes that extend ArrayObject?

### ISSUE THREAD

**Issue by alezha** [kint-php/kint#329] opened 2020-01-28 01:51 UTC
When dumping an object whose class extends \ArrayObject, only the \ArrayObject variables get dumped.  Code:

```php
$test = new TestClass();
$test->append('test');

/**
 * +\Kint::dump excludes $test->isa, whereas var_dump shows it.
 */
+\Kint::dump($test);
var_dump($test);

class TestClass extends \ArrayObject
{
    public bool $isa = false;
}
```

Output screenshot: https://imgur.com/a/LNEzEhB

Dunno if this is related to https://github.com/kint-php/kint/issues/232 or if I'm using Kint incorrectly.

**Comment by jnvsor** [comment] 2020-01-28 06:20
The `ArrayObjectPlugin` sets `ArrayObject::STD_PROP_LIST` before parsing to ensure this *doesn't* happen. I'll look into it thanks for the report

**Comment by alezha** [comment] 2020-01-28 09:38
Awesome, glad to be of help!

**Comment by jnvsor** [comment] 2020-01-28 17:47
Ugh. I'm not sure how/when this happened but it looks like it needs to be parsed twice - once with `ArrayObject::STD_PROP_LIST` to get your `isa` (Which isn't working for some reason) and once with `ArrayObject::ARRAY_AS_PROPS` to get the contents.

This will take a bit of work. I probably won't get to it until the weekend (And when I do it will be going onto the unreleased 4.x branch)

**Comment by alezha** [comment] 2020-01-29 04:52
Ah I see.  Sounds good, thanks for your work!

**Comment by jnvsor** [comment] 2020-02-01 13:06
@alezha I've figured out what's going wrong.

Normally when you dump an `ArrayObject` you'll see the properties in the properties tab, and the array elements in the iterator tab. *This works as intended*

So what's going wrong then? Well for starters you're dumping in plain mode:

We can't show more than one data representation at a time in text mode without having a special case for every class. This isn't a problem for `var_dump` because it has access to the underlying `ArrayObject` implementation. (Hence the strange `"storage":"ArrayObject":private` that doesn't exist when casting to array)

The `TextRenderer` that handles plain-text dumps has a plugin whitelist because you can't display as much information in text as in rich mode anyway, so it's a waste of time parsing things you won't display anyway.

Unfortunately, I forgot to put `ArrayObject` on that whitelist, so it ends up dumping the iterable contents instead of the properties. Fixing that has the expected result of showing the properties, and not the iterator results.

If you want to see both, you'll have to use rich mode, or make your own text renderer plugin.

Anyway, fixed in b8acac7c9b767d8c9da56db3b8827e9c8a9d6205 (There's room for improvement by putting the iterator contents under the mysteriously missing storage private at some point)

**Closed as completed by jnvsor** 2020-02-01 13:06 UTC

**Comment by raveren** [comment] 2020-02-02 02:17
> This will take a bit of work. I probably won't get to it until the weekend (And when I do it will be going onto the **unreleased 4.x branch**)

Please, for the love of sanity, make the fold off by default in the next major release 🙈

**Comment by jnvsor** [comment] 2020-02-02 10:53
@raveren It already is off by default on master - that wasn't the brightest move on my part
